version: '3.8'

services:

  web:
    image: projectsidewalk/web
    container_name: projectsidewalk-web
    build:
      context: ./
    depends_on:
      - db
    volumes:
      - "./:/opt/:delegated"
      - "/opt/node_modules"
    ports:
      - "9000:9000"
    platform: linux/x86_64
    environment:
      - DATABASE_URL=jdbc:postgresql://db:5432/sidewalk
      - SIDEWALK_CITY_ID=${SIDEWALK_CITY_ID}               # pick up the environmental in .env file
      - SIDEWALK_EMAIL_ADDRESS=${SIDEWALK_EMAIL_ADDRESS}   # pick up the environmental in .env file
      - SIDEWALK_EMAIL_PASSWORD=${SIDEWALK_EMAIL_PASSWORD} # pick up the environmental in .env file
      - GOOGLE_MAPS_API_KEY=${GOOGLE_MAPS_API_KEY}         # pick up the environmental variable on path
      - GOOGLE_MAPS_SECRET=${GOOGLE_MAPS_SECRET}           # pick up the environmental variable on path
      - INTERNAL_API_KEY=INTERNAL_API_KEY                  # pick up the environmental in .env file
      - ENV_TYPE=test

  db:
    image: projectsidewalk/db
    container_name: projectsidewalk-db
    build:
      context: ./db/
    volumes:
      - "./db/init.sh:/docker-entrypoint-initdb.d/init.sh"
      - "./db:/opt"
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=sidewalk
